# Generated by Django 3.2.2 on 2021-12-07 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_alter_leavereportstaffs_leave_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
